/**
 * Created by atmaramn on 7/13/17.
 */
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const UNREGISTER_SUCCESS="UNREGISTER_SUCCESS";
export const ROLES_SUCCESS="ROLES_SUCCESS";
export const PROFILE_SUCCESS="PROFILE_SUCCESS";