/**
 * Created by atmaramn on 7/19/17.
 */
export const PRODUCTS_LOAD_SUCCESS="PRODUCTS_LOAD_SUCCESS";
export const PRODUCT_STOCK_LOAD_SUCCESS="PRODUCT_STOCK_LOAD_SUCCESS";
export const PRODUCT_BUY_SUCCESS="PRODUCT_BUY_SUCCESS";